# This file is not meant for public use and will be removed in SciPy v2.0.0.
# Use the `scipy.spatial` namespace for importing the functions
# included below.
from typing_extensions import deprecated

__all__: list[str] = ["ConvexHull", "Delaunay", "HalfspaceIntersection", "QhullError", "Voronoi", "tsearch"]

class QhullError(RuntimeError): ...

@deprecated("will be removed in SciPy v2.0.0")
class _QhullUser:
    def __init__(self, qhull: object, incremental: object = ...) -> None: ...
    def close(self) -> None: ...
    def _update(self, qhull: object) -> None: ...
    def _add_points(self, points: object, restart: object = ..., interior_point: object = ...) -> None: ...

class ConvexHull(_QhullUser):
    def __init__(self, points: object, incremental: object = ..., qhull_options: object = ...) -> None: ...
    def _update(self, qhull: object) -> None: ...
    def add_points(self, points: object, restart: object = ...) -> None: ...
    @property
    def points(self) -> object: ...
    @property
    def vertices(self) -> object: ...

class Delaunay(_QhullUser):
    def __init__(
        self, points: object, furthest_site: object = ..., incremental: bool = ..., qhull_options: object = ...
    ) -> None: ...
    def _update(self, qhull: object) -> None: ...
    def add_points(self, points: object, restart: object = ...) -> None: ...
    @property
    def points(self) -> object: ...
    @property
    def transform(self) -> object: ...
    @property
    def vertex_to_simplex(self) -> object: ...
    @property
    def vertex_neighbor_vertices(self) -> object: ...
    @property
    def convex_hull(self) -> object: ...
    def find_simplex(self, xi: object, bruteforce: object = ..., tol: object = ...) -> object: ...
    def plane_distance(self, xi: object) -> object: ...
    def lift_points(self, x: object) -> object: ...

class HalfspaceIntersection(_QhullUser):
    def __init__(
        self, halfspaces: object, interior_point: object, incremental: object = ..., qhull_options: object = ...
    ) -> None: ...
    def _update(self, qhull: object) -> None: ...
    def add_halfspaces(self, halfspaces: object, restart: object = ...) -> None: ...
    @property
    def halfspaces(self) -> object: ...
    @property
    def dual_vertices(self) -> object: ...

class Voronoi(_QhullUser):
    def __init__(
        self, points: object, furthest_site: object = ..., incremental: object = ..., qhull_options: object = ...
    ) -> None: ...
    def _update(self, qhull: object) -> None: ...
    def add_points(self, points: object, restart: object = ...) -> None: ...
    @property
    def points(self) -> object: ...
    @property
    def ridge_dict(self) -> dict[tuple[int, int], list[int]]: ...

def tsearch(tri: Delaunay, xi: object) -> object: ...
